export type Language = 'en' | 'zh-TW';

export const translations = {
  en: {
    // Header
    appName: 'Edu-Analyst',
    appSubtitle: 'AI',
    viewHistory: 'View History',

    // Main section
    mainTitle: 'Scholarly Video Analysis',
    mainSubtitle: 'Paste a YouTube URL or transcript below to receive a high-level educational synthesis, curated by advanced semantic models.',
    inputPlaceholder: 'Paste YouTube URL or long transcript text here...',
    analyzeButton: 'Analyze',

    // Document upload
    documentSummary: 'Document Summary',
    documentTypes: 'PDF, DOCX, or TXT files',
    chooseDocument: 'Choose a document',
    summarizeButton: 'Summarize',
    words: 'words',

    // Image upload
    imageAnalysis: 'Image Analysis',
    imageTypes: 'PNG, JPG, GIF, or WebP files',
    chooseImage: 'Choose an image',

    // Audio upload
    audioAnalysis: 'Audio Analysis',
    audioTypes: 'MP3, WAV, OGG, M4A, or FLAC files',
    chooseAudio: 'Choose an audio file',

    // Transcript input
    transcriptAnalysis: 'Transcript Analysis',
    transcriptPlaceholder: 'Paste your video transcript here for educational analysis...',
    transcriptDescription: 'Paste YouTube or video transcript text',

    // Status badges
    statusFetching: 'Retrieving Video Transcript...',
    statusAnalyzing: 'Cognitive Processing...',
    statusSummarizing: 'Synthesizing Analysis...',
    statusCompleted: 'Analysis Ready',
    statusError: 'Analysis Failed',

    // Error state
    errorTitle: 'Analysis Interrupted',
    dismissButton: 'Dismiss',

    // Results
    educationalThesis: 'Educational Thesis',
    analysisReport: 'Analysis Report',
    generatedOn: 'Generated on',
    copyText: 'Copy Text',
    copiedAlert: 'Analysis copied to clipboard!',
    analysisFooter: 'Analysis provided by Gemini 2.5 Flash. Primary focus: Pedagogy, Concepts, and Application.',

    // Empty state
    emptyStateText: 'Enter a source above to begin your deep analysis.',

    // History
    historyTitle: 'Analysis History',
    noHistoryFound: 'No recent analyses found.',
    clearAllHistory: 'Clear All History',

    // Footer
    footerDescription: 'A specialized academic utility designed for rapid synthesis of educational media. All insights are generated by AI and should be verified for mission-critical applications.',

    // Language toggle
    switchLanguage: 'Switch to Chinese',
  },
  'zh-TW': {
    // Header
    appName: '教育分析師',
    appSubtitle: 'AI',
    viewHistory: '查看歷史記錄',

    // Main section
    mainTitle: '學術影片分析',
    mainSubtitle: '在下方貼上 YouTube 網址或文字稿，即可獲得由先進語義模型精選的高階教育綜合分析。',
    inputPlaceholder: '在此貼上 YouTube 網址或長文字稿...',
    analyzeButton: '分析',

    // Document upload
    documentSummary: '文件摘要',
    documentTypes: 'PDF、DOCX 或 TXT 檔案',
    chooseDocument: '選擇文件',
    summarizeButton: '摘要',
    words: '字',

    // Image upload
    imageAnalysis: '圖片分析',
    imageTypes: 'PNG、JPG、GIF 或 WebP 檔案',
    chooseImage: '選擇圖片',

    // Audio upload
    audioAnalysis: '音訊分析',
    audioTypes: 'MP3、WAV、OGG、M4A 或 FLAC 檔案',
    chooseAudio: '選擇音訊檔案',

    // Transcript input
    transcriptAnalysis: '文字稿分析',
    transcriptPlaceholder: '在此貼上影片文字稿以進行教育分析...',
    transcriptDescription: '貼上 YouTube 或影片文字稿',

    // Status badges
    statusFetching: '正在擷取影片字幕...',
    statusAnalyzing: '認知處理中...',
    statusSummarizing: '正在綜合分析...',
    statusCompleted: '分析完成',
    statusError: '分析失敗',

    // Error state
    errorTitle: '分析中斷',
    dismissButton: '關閉',

    // Results
    educationalThesis: '教育論述',
    analysisReport: '分析報告',
    generatedOn: '生成於',
    copyText: '複製文字',
    copiedAlert: '分析已複製到剪貼簿！',
    analysisFooter: '分析由 Gemini 2.5 Flash 提供。主要聚焦：教學法、概念與應用。',

    // Empty state
    emptyStateText: '在上方輸入來源以開始深度分析。',

    // History
    historyTitle: '分析歷史',
    noHistoryFound: '找不到最近的分析記錄。',
    clearAllHistory: '清除所有歷史記錄',

    // Footer
    footerDescription: '一個專為快速綜合教育媒體而設計的專業學術工具。所有見解均由 AI 生成，重要應用時應加以驗證。',

    // Language toggle
    switchLanguage: '切換至英文',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function getTranslation(lang: Language, key: TranslationKey): string {
  return translations[lang][key];
}
